# Generated by Django 5.2 on 2025-05-12 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_location_device_alter_location_timestamp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='serial_number',
            new_name='device_id',
        ),
        migrations.AlterField(
            model_name='deviceassignment',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='devices.device'),
        ),
        migrations.AlterField(
            model_name='deviceassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to=settings.AUTH_USER_MODEL),
        ),
    ]
